### ISSUE TITLE
Compilation error in Arduino IDE 

### ISSUE THREAD

**Issue by ghost** [xoseperez/eeprom32_rotate#8] opened 2022-02-28 22:15 UTC
Hi there I have this compile error which I'm unsure how to resolve. Can somebody help? I was compiling the basic example in this case. 
https://github.com/xoseperez/eeprom32_rotate/blob/master/examples/basic/basic.ino

Error here:
```
In file included from D:\Desktop\EEPROM32_ROTATE\EEPROM32_ROTATE.ino:5:
C:\Program Files (x86)\Arduino\portable\packages\esp32\hardware\esp32\2.0.2\libraries\eeprom32_rotate\src/EEPROM32_Rotate.h: In constructor 'EEPROM32_Rotate::EEPROM32_Rotate()':
C:\Program Files (x86)\Arduino\portable\packages\esp32\hardware\esp32\2.0.2\libraries\eeprom32_rotate\src/EEPROM32_Rotate.h:52:13: error: '_user_defined_size' was not declared in this scope
             _user_defined_size = 0;
             ^~~~~~~~~~~~~~~~~~
```

Full compile log attached. 

[EEPROM32_rotate bad compile output.txt](https://github.com/xoseperez/eeprom32_rotate/files/8158547/EEPROM32_rotate.bad.compile.output.txt)

**Comment by denisvitez** [comment] 2023-05-09 19:33
I'm facing the same issue, did you manage to solve it?

**Comment by xoseperez** [comment] 2023-05-09 19:55
Please check the latest code in master branch.

**Comment by TupaNegreiros** [comment] 2023-08-13 18:15
Version 0.9.4, latest available in Arduino IDE, issue persists.

**Comment by dirkvranckaert** [comment] 2024-11-06 10:10
Any update? The issue is still there...

**Comment by xoseperez** [comment] 2024-11-06 10:46
Hi @dirkvranckaert
It should be enough with deleting the constructor in the header file, but I cannot test it right now:

```
diff --git a/src/EEPROM32_Rotate.h b/src/EEPROM32_Rotate.h
index 516d13a..3f3d2d1 100644
--- a/src/EEPROM32_Rotate.h
+++ b/src/EEPROM32_Rotate.h
@@ -47,10 +47,6 @@ class EEPROM32_Rotate: public EEPROMClass {
 
     public:
 
-        EEPROM32_Rotate(): EEPROMClass() {
-            _user_defined_size = 0;
-        };
-
         uint8_t add_by_name(const char* name);
         uint8_t add_by_subtype(uint8_t subtype);
         bool offset(uint16_t offset);
```

**Comment by dirkvranckaert** [comment] 2024-11-07 08:19
@xoseperez That works in that location, but here are quite some more references to `_user_defined_size` : 

```
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member function 'uint8_t EEPROM32_Rotate::add_by_name(const char*)':
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:48:15: error: '_user_defined_size' was not declared in this scope
   48 |     if ((0 == _user_defined_size) || (part->size < _user_defined_size)) {
      |               ^~~~~~~~~~~~~~~~~~
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member function 'uint8_t EEPROM32_Rotate::add_by_subtype(uint8_t)':
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:86:19: error: '_user_defined_size' was not declared in this scope
   86 |         if ((0 == _user_defined_size) || (part->size < _user_defined_size)) {
      |                   ^~~~~~~~~~~~~~~~~~
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member function 'bool EEPROM32_Rotate::offset(uint16_t)':
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:118:22: error: '_user_defined_size' was not declared in this scope
  118 |     if (offset + 3 > _user_defined_size) return false;
      |                      ^~~~~~~~~~~~~~~~~~
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member function 'bool EEPROM32_Rotate::commit()':
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:275:10: error: '_user_defined_size' was not declared in this scope
  275 |     if (!_user_defined_size) return false;
      |          ^~~~~~~~~~~~~~~~~~
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member function 'uint16_t EEPROM32_Rotate::_calculate_crc()':
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:340:42: error: '_user_defined_size' was not declared in this scope
  340 |     for (uint16_t address = 0; address < _user_defined_size; address++) {
      |                                          ^~~~~~~~~~~~~~~~~~

```

**Comment by xoseperez** [comment] 2024-11-08 07:23
@dirkvranckaert 
What version of Arduino IDE are you using? Just tested it with 1.8.19 and 2.3.2 and both compiled the basic example without issue. PlatformIO also compiles it fine. Right now I cannot reproduce the problem.

**Comment by dirkvranckaert** [comment] 2024-11-12 11:47
I'm on Arduino IDE 2.3.3 using the "ESP32C6 Dev Module" board. Seeing these
errors

[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member
function 'uint8_t EEPROM32_Rotate::add_by_name(const char*)':
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:48:15:
error: '_user_defined_size' was not declared in this scope
   48 |     if ((0 == _user_defined_size) || (part->size <
_user_defined_size)) {
      |               ^~~~~~~~~~~~~~~~~~
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member
function 'uint8_t EEPROM32_Rotate::add_by_subtype(uint8_t)':
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:86:19:
error: '_user_defined_size' was not declared in this scope
   86 |         if ((0 == _user_defined_size) || (part->size <
_user_defined_size)) {
      |                   ^~~~~~~~~~~~~~~~~~
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member
function 'bool EEPROM32_Rotate::offset(uint16_t)':
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:118:22:
error: '_user_defined_size' was not declared in this scope
  118 |     if (offset + 3 > _user_defined_size) return false;
      |                      ^~~~~~~~~~~~~~~~~~
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member
function 'bool EEPROM32_Rotate::commit()':
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:275:10:
error: '_user_defined_size' was not declared in this scope
  275 |     if (!_user_defined_size) return false;
      |          ^~~~~~~~~~~~~~~~~~
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member
function 'uint16_t EEPROM32_Rotate::_calculate_crc()':
[PATH]/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:340:42:
error: '_user_defined_size' was not declared in this scope
  340 |     for (uint16_t address = 0; address < _user_defined_size;
address++) {
      |                                          ^~~~~~~~~~~~~~~~~~

exit status 1

Compilation error: exit status 1

Op vr 8 nov 2024 om 08:23 schreef Xose Pérez ***@***.***>:

**Comment by xoseperez** [comment] 2024-11-12 12:21
Interesting, same version and compiling against the same board here works. Maybe it's an OS thing? 
The _user_defined_size is defined as protected to the class.
Are there any other warnings before that might explain why it's not defined?

**Comment by dirkvranckaert** [comment] 2024-11-12 18:45
No, that's the only output I'm getting. Not a single extra warning...

Here is the output throught arduino-cli:

➜  InstallationProgram git:(develop) ✗ arduino-build-esp32c6
> ~/Downloads/TEST
> No local.properties, falling back to default arduino-cli
> Compiling 'InstallationProgram.ino' for ESP32-C6 to [PATH]/Downloads/TEST
> ...
> [PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:
> In member function 'uint8_t EEPROM32_Rotate::add_by_name(const char*)':
> [PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:48:15:
> error: '_user_defined_size' was not declared in this scope
>    48 |     if ((0 == _user_defined_size) || (part->size <
> _user_defined_size)) {
>       |               ^~~~~~~~~~~~~~~~~~
> [PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:
> In member function 'uint8_t EEPROM32_Rotate::add_by_subtype(uint8_t)':
> [PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:86:19:
> error: '_user_defined_size' was not declared in this scope
>    86 |         if ((0 == _user_defined_size) || (part->size <
> _user_defined_size)) {
>       |                   ^~~~~~~~~~~~~~~~~~
> [PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:
> In member function 'bool EEPROM32_Rotate::offset(uint16_t)':
> [PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:118:22:
> error: '_user_defined_size' was not declared in this scope
>   118 |     if (offset + 3 > _user_defined_size) return false;
>       |                      ^~~~~~~~~~~~~~~~~~
> [PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:
> In member function 'bool EEPROM32_Rotate::commit()':
> [PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:275:10:
> error: '_user_defined_size' was not declared in this scope
>   275 |     if (!_user_defined_size) return false;
>       |          ^~~~~~~~~~~~~~~~~~
> [PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:
> In member function 'uint16_t EEPROM32_Rotate::_calculate_crc()':
> [PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:340:42:
> error: '_user_defined_size' was not declared in this scope
>   340 |     for (uint16_t address = 0; address < _user_defined_size;
> address++) {
>       |                                          ^~~~~~~~~~~~~~~~~~
>
>
> Used library        Version Path
> ArduinoJson         6.20.0  [PATH]/Documents/Arduino/libraries/ArduinoJson

WiFi                3.1.0
>  [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.1.0-RC2/libraries/WiFi

Networking          3.1.0
>  [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.1.0-RC2/libraries/Network

HTTPClient          3.1.0
>  [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.1.0-RC2/libraries/HTTPClient

NetworkClientSecure 3.1.0
>  [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.1.0-RC2/libraries/NetworkClientSecure

EEPROM32_Rotate     0.9.4
>  [PATH]/Documents/Arduino/libraries/EEPROM32_Rotate

EEPROM              3.1.0
>  [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.1.0-RC2/libraries/EEPROM

LittleFS            3.1.0
>  [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.1.0-RC2/libraries/LittleFS

FS                  3.1.0
>  [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.1.0-RC2/libraries/FS

Adafruit NeoPixel   1.12.3
> [PATH]/Documents/Arduino/libraries/Adafruit_NeoPixel

Time                1.6.1   [PATH]/Documents/Arduino/libraries/Time


> Used platform Version   Path
> esp32:esp32   3.1.0-RC2
> [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.1.0-RC2

Error during build: exit status 1
>

I'm compiling from MAC OS Sonoma 14.3.
Anything I can change to try to to make it work?

Op di 12 nov 2024 om 13:21 schreef Xose Pérez ***@***.***>:

**Comment by xoseperez** [comment] 2024-11-13 07:29
I see you are using esp32 3.1.0-RC2 while I use the latest stable 3.0.5. Do you mind testing it with the stable branch?

**Comment by dirkvranckaert** [comment] 2024-11-13 20:39
Latest stable is 3.0.7, however tested with 3.0.7 as well as 3.0.5, output is from this 3.0.5 test but exactly the same:

```
[PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member function 'uint8_t EEPROM32_Rotate::add_by_name(const char*)':
[PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:48:15: error: '_user_defined_size' was not declared in this scope
   48 |     if ((0 == _user_defined_size) || (part->size < _user_defined_size)) {
      |               ^~~~~~~~~~~~~~~~~~
[PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member function 'uint8_t EEPROM32_Rotate::add_by_subtype(uint8_t)':
[PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:86:19: error: '_user_defined_size' was not declared in this scope
   86 |         if ((0 == _user_defined_size) || (part->size < _user_defined_size)) {
      |                   ^~~~~~~~~~~~~~~~~~
[PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member function 'bool EEPROM32_Rotate::offset(uint16_t)':
[PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:118:22: error: '_user_defined_size' was not declared in this scope
  118 |     if (offset + 3 > _user_defined_size) return false;
      |                      ^~~~~~~~~~~~~~~~~~
[PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member function 'bool EEPROM32_Rotate::commit()':
[PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:275:10: error: '_user_defined_size' was not declared in this scope
  275 |     if (!_user_defined_size) return false;
      |          ^~~~~~~~~~~~~~~~~~
[PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp: In member function 'uint16_t EEPROM32_Rotate::_calculate_crc()':
[PATH]/Documents/Arduino/libraries/EEPROM32_Rotate/src/EEPROM32_Rotate.cpp:340:42: error: '_user_defined_size' was not declared in this scope
  340 |     for (uint16_t address = 0; address < _user_defined_size; address++) {
      |                                          ^~~~~~~~~~~~~~~~~~


Used library        Version Path
ArduinoJson         6.20.0  [PATH]/Documents/Arduino/libraries/ArduinoJson
WiFi                3.0.5   [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/WiFi
Networking          3.0.5   [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/Network
HTTPClient          3.0.5   [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/HTTPClient
NetworkClientSecure 3.0.5   [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/NetworkClientSecure
EEPROM32_Rotate     0.9.4   [PATH]/Documents/Arduino/libraries/EEPROM32_Rotate
EEPROM              3.0.5   [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/EEPROM
LittleFS            3.0.5   [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/LittleFS
FS                  3.0.5   [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/FS
Adafruit NeoPixel   1.12.3  [PATH]/Documents/Arduino/libraries/Adafruit_NeoPixel
Time                1.6.1   [PATH]/Documents/Arduino/libraries/Time

Used platform Version Path
esp32:esp32   3.0.5   [PATH]/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5
Error during build: exit status 1
```

**Comment by dirkvranckaert** [comment] 2024-11-13 21:33
And just to make sure there is no side-effect from the other libs or so I have a bare sketch like this:

```
#include <EEPROM32_Rotate.h>

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
```

And when compiling I get the exact same errors, but in the libs and platform it only outputs (after the same errors obviously):

```
Used library    Version Path
EEPROM32_Rotate 0.9.4   /Users/dirkvranckaert/Documents/Arduino/libraries/EEPROM32_Rotate
EEPROM          3.0.5   /Users/dirkvranckaert/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/EEPROM

Used platform Version Path
esp32:esp32   3.0.5   /Users/dirkvranckaert/Library/Arduino15/packages/esp32/hardware/esp32/3.0.5
```

**Comment by dirkvranckaert** [comment] 2024-11-18 11:18
@xoseperez Did you get a chance to look at my previous finding already?

**Comment by xoseperez** [comment] 2024-11-18 14:07
Yes, it was a problem with the versioning. The latest changes (from 2019!) where not published to Arduino.
I'm sorry for the trouble. Should be fixed once you can update to version 0.9.5.

**Comment by dirkvranckaert** [comment] 2024-11-19 10:46
@xoseperez Great! Thanks! It seems to be working. Though I needed to install it manually with the zip instead of using the library manager (that one was still on 0.9.4).

**Comment by dirkvranckaert** [comment] 2024-11-19 10:51
Oh nevermind, a restart today of Arduino IDE made it show up in the dependencies also! So seems this can be closed!?

**Comment by xoseperez** [comment] 2024-11-19 13:01
Sure, thank you!

**Closed as completed by xoseperez** 2024-11-19 13:01 UTC
